### PR TITLE
convert block:parameters sections to markdown tables

### PR DESCRIPTION
**Pull request by starbelly**
Ok, so before we convert every page I wanted you to see what this looks like. It may be the better route to go still is using shortcodes and/or partials with scratch pad variables and/or data files.

### CODE REVIEW

**Comment by starbelly** [comment]
Yeah, after looking at this diff... I'd be more in favor of not using markdown tables for this, it's just too messy. I mean, what's rendered is fine, but it's very hard to read if you're editing the source. That's my 2 cents.

**Comment by starbelly** [comment]
On second though, we shall make it work 😄

**Comment by starbelly** [comment]
@tsloughter Ok, this is ready for a review. Probably a few minor things missed.

**Comment by tsloughter** [comment]
Woo, thanks, this is great!

**Pull request merged**
